version: '2'
services:
    777-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/777/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=777
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
